name: iOS CI

on:
  push:
    paths:
      - "ios/julis-sh-intern-ios/**"
  pull_request:
    paths:
      - "ios/julis-sh-intern-ios/**"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Install dependencies (CocoaPods, falls benötigt)
        run: |
          cd ios/julis-sh-intern-ios
          pod install || true
      - name: Build app
        run: |
          cd ios/julis-sh-intern-ios
          xcodebuild -scheme julis-sh-intern-ios -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build
      # - name: Run tests (optional)
      #   run: |
      #     cd ios/julis-sh-intern-ios
      #     xcodebuild test -scheme julis-sh-intern-ios -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
